import {qualificationDisplayText} from './political-qualification.js';
import {endpointReviewEntry} from './endpoint-review.js';
import {supersededModelNote} from './records.js';
import {createPublicDisplay,noticeKey} from './public-display.js';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,assessments,research,actors,rows,namesZh,chronology,publicView,endpointReviewRegistry;
const publicRecord=r=>publicView.record(r,{surface:'continuity'});
const displayRecordTitle=r=>publicRecord(r).title;
const publicDate=r=>publicRecord(r).dateLabel;
const publicDescription=r=>publicRecord(r).description;
function publicNotice(file,segments,original){const n=publicView.notice(noticeKey(file,...segments),original),description=qualificationDisplayText(n.description);return `<span>${esc(description)}</span>${n.scopeLabel?`<p class="audit-inference">${esc(n.scopeLabel)}</p>`:''}${description!==n.original?`<details><summary>原说明与研究依据</summary><p>${esc(n.original)}</p></details>`:''}`;}
function originalRecord(r){const p=publicRecord(r);return `<p class="audit-inference">${esc([p.dateLabel,p.certaintyLabel,p.scopeLabel,p.sourceWindowLabel].filter(Boolean).join(' · '))}</p><details><summary>原记录与研究说明</summary><p>${esc(p.original.title)}</p><p>${esc(p.original.description)}</p>${p.original.geometryNote?`<p>${esc(p.original.geometryNote)}</p>`:''}${p.original.reasoning?`<p>${esc(p.original.reasoning)}</p>`:''}${(r.alternatives||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</details>`;}

const kind={setup:'官方开局',continued:'旧界延续推测',reconstructed:'史料节点／省形投影',anchored:'锚点约束的连续段',hypothesis:'合理推测',unresolved:'资料未定'};
const name=tag=>tag?(actors[tag]?.nameZh||actors[tag]?.name||tag):'未指定所有者';
// Use the interval's identity, retaining the existing Chinese localization only
// when its English name is unchanged from the actor catalogue.
const intervalName=i=>i.ownerNameZh||(i.ownerName&&i.ownerName!==actors[i.owner]?.name?i.ownerName:name(i.owner));
function sources(ids){return (ids||[]).map(id=>data.sources[id]).filter(Boolean).map(s=>/^https?:\/\//.test(s.url||'')?`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title||s.path)} ↗</a>`:`<span>${esc(s.title||s.path)}${s.path?` · ${esc(s.path)}`:''}${s.sha256?` · SHA256 ${esc(s.sha256)}`:''}</span>`).join('<br>');}
function showCountry(){
 const a=assessments.countries[$('audit-country').value];if(!a){$('audit-country-detail').innerHTML='';return;}
 const country=research.countries.find(c=>c.id===a.countryId);
 $('audit-country-detail').innerHTML=`<h3>${esc(country?.name_zh||country?.name||a.countryId)}</h3><p class="audit-inference">${publicNotice('reconstruction-assessments',['countries',a.countryId,'summary'],a.summary)}</p><p>${esc(a.classification||'已审推演')}</p><p><a href="./research.html#country=${encodeURIComponent(a.countryId)}">查看国家资料与史实审校 →</a></p><h4>采用的阶段</h4><ul>${(a.stepIds||[]).map(id=>research.records[id]).filter(Boolean).map(r=>`<li><a href="./?year=${r.year}&country=${encodeURIComponent(country?.tag||'')}&dossier=${encodeURIComponent(country?.origin.dossierTag||country?.tag||'')}">${esc(publicDate(r))} · ${esc(displayRecordTitle(r))}</a>${originalRecord(r)}</li>`).join('')||'<li>本方案维持已核或最近状态，或将该主体作为地方／条件模板登记；不为它另造独立疆域。</li>'}</ul><details><summary>仍属于历史不确定性</summary><ul>${(a.uncertainties||[]).map((x,j)=>`<li>${publicNotice('reconstruction-assessments',['countries',a.countryId,'uncertainties',j],x)}</li>`).join('')}</ul><div class="audit-source">${sources(a.sourceIds)}</div></details>`;
}
function showProvince(){
 const row=data.provinces.find(p=>p.id===Number($('audit-province').value));if(!row){$('audit-province-detail').innerHTML='<p>没有匹配省份。</p>';return;}
 const rowIndex=data.provinces.indexOf(row);
 const seamIndex=(data.seamExceptions||[]).findIndex(item=>item.provinceId===row.id);
 const seam=data.seamExceptions?.[seamIndex];
 const review=endpointReviewEntry(endpointReviewRegistry,row.id,1820);
 const seamOpen=(data.unresolvedSeamProvinceIds||[]).includes(row.id);
 const params=new URLSearchParams(location.search);params.set('province',row.id);if($('audit-country').value)params.set('country',$('audit-country').value);else params.delete('country');history.replaceState(null,'',`?${params}`);
 $('audit-province-detail').innerHTML=`<h3>${esc(row.nameZh?row.nameZh+' / '+row.name:row.name)} · ${row.id}</h3><p class="subtle">${esc(row.region)} · 各段首尾连续；同一所有者也可能因附属关系、身份或依据改变而分段。</p>${review?`<p class="audit-inference"><strong>端点说明</strong><br>${publicNotice('haless-quality-endpoint-label',[review.decisionId],review.publicText)} <a href="./endpoint-review.html?province=${row.id}">查看原始对照与裁决</a></p>${review.displayPolicy==='withhold-conflicted-projection'?'<p class="audit-inference">1820默认地图暂不为此省指定主权；下列连续记录保留原方案，1820行仅供原批对照。</p>':''}`:''}${seam?`<p class="audit-inference"><strong>${seamOpen?'1819—1820仍有未决衔接':'原接缝研究记录 · 当前显示已衔接'}</strong><br>${seamOpen?'':'当前方案已衔接显示；下列原记录保留此前的资料缺口，不能据此断言目前仍未入图。推测衔接不等于史实确证。<br>'}${publicNotice('continuity',['seamExceptions',seamIndex,'reason'],seam.reason)}</p><div class="audit-source">${sources(seam.sourceIds)}</div>`:''}<div class="audit-table"><table><thead><tr><th>年份</th><th>显示归属</th><th>依据与推理</th></tr></thead><tbody>${row.intervals.map((i,intervalIndex)=>{
 const record=research.records[i.recordId];
 const modelNote=record?supersededModelNote(record,chronology.modelSupersessions,chronology.modelReviewNotes):'';
 const identity=research.records[i.identityRecordId];
 const settlement=research.records[i.settlementEvidence?.recordId];
 const settlementMarkup=settlement?`<p class="audit-inference"><strong>定居进程：${esc(publicDate(settlement))} · ${esc(displayRecordTitle(settlement))}</strong><br>${esc(publicDescription(settlement))}${originalRecord(settlement)}<br>定居变化与领土接管分别记录。</p>`:'';
 const identityMarkup=identity?`<p class="audit-inference"><strong>名称与旗色依据：${esc(publicDate(identity))} · ${esc(displayRecordTitle(identity))}</strong><br>${esc(publicDescription(identity))}${originalRecord(identity)}${identity.dateEvidence?.dateIsHistoricalFact===false?'<br>此处采用展示观察年；具体名称或旗色采用日期未被确证。':''}</p>`:'';
 const support=(i.certaintySupport||[]).map((s,supportIndex)=>`<p class="audit-inference">${s.anchorYear}年锚点 · ${s.dimensions.includes('ownership')?'归属':'统治关系'}：${esc(research.records[s.anchorRecordId]?displayRecordTitle(research.records[s.anchorRecordId]):s.anchorRecordId)}。${publicNotice('continuity',['provinces',rowIndex,'intervals',intervalIndex,'certaintySupport',supportIndex,'reason'],s.reason)}</p>`).join('');
 return `<tr><td class="audit-interval">${i.start}${i.end!==i.start?'—'+i.end:''}<br><a href="./?year=${i.start}&country=${encodeURIComponent(i.start===1820?(data.endpointInferences.find(x=>x.provinceId===row.id)?.owner||row.endpointEvidence?.owner||''):(i.owner||''))}">查看地图</a></td><td>${esc(intervalName(i))}${i.overlord?`<p class="subtle">宗主：${esc(name(i.overlord))}${i.overlordOutsideCoverage?'（范围外关系）':''}</p>`:''}${i.relationChain?.length>1?`<p class="subtle">完整统治链：${[i.owner,...i.relationChain.map(r=>r.overlord)].map((t,index)=>esc(index===0?intervalName(i):name(t))).join(' → ')}</p>`:''}<p class="audit-kind">${esc(kind[i.kind]||i.kind)}</p></td><td>${record?`<strong>${esc(displayRecordTitle(record))}</strong><p>${esc(publicDescription(record))}${originalRecord(record)}</p>`:''}${i.reason!==record?.description?`<p>${publicNotice('continuity',['provinces',rowIndex,'intervals',intervalIndex,'reason'],i.reason)}</p>`:''}${modelNote?`<p class="audit-inference">${esc(modelNote)}</p>`:''}${record?.reasoning?`<details><summary>推理与备选解释</summary><p>${esc(record.reasoning)}</p>${(record.alternatives||[]).map(a=>`<p>${esc(a)}</p>`).join('')}</details>`:''}${identityMarkup}${i.nameEvidence?`<p class="audit-inference"><strong>1820动态名称依据</strong><br>${publicNotice('continuity',['provinces',rowIndex,'intervals',intervalIndex,'nameEvidence','basis'],i.nameEvidence.basis)}</p>`:''}${settlementMarkup}${support}<details><summary>来源与追溯点</summary><p class="audit-source">领土与关系：${esc(i.recordId)}${i.identityRecordId?`<br>名称与旗色：${esc(i.identityRecordId)}`:''}</p><div class="audit-source">${sources(i.sourceIds)}</div></details></td></tr>`;
 }).join('')}</tbody></table></div>`;
}
function filterProvinces(){const q=$('audit-search').value.trim().toLocaleLowerCase(),selected=$('audit-province').value;rows=data.provinces.filter(p=>`${p.id} ${p.name} ${p.nameZh} ${p.region}`.toLocaleLowerCase().includes(q));$('audit-province').innerHTML=rows.map(p=>`<option value="${p.id}">${p.id} · ${esc(p.nameZh?p.nameZh+' / '+p.name:p.name)}</option>`).join('');if(rows.some(p=>String(p.id)===selected))$('audit-province').value=selected;showProvince();}
try{
 [data,assessments,research,actors,namesZh]=await Promise.all(['continuity','reconstruction-assessments','research-index','atlas','names-zh'].map(async file=>{const r=await fetch(`./data/${file}.json`);if(!r.ok)throw new Error(file);return r.json();}));
 actors=actors.countries;chronology=await (await fetch('./data/western-chronology.json')).json();endpointReviewRegistry=await (await fetch('./data/endpoint-review.json')).json();publicView=createPublicDisplay({copy:await (await fetch('./data/public-copy.json')).json(),steps:chronology.steps});actors={...actors,...chronology.actors};for(const [tag,actor] of Object.entries(actors))actor.nameZh ||= namesZh.countries[tag];for(const p of data.provinces)p.nameZh=namesZh.provinces[p.id]||'';
 $('audit-summary').innerHTML=`<div><strong>${data.subjectCount}</strong><small>主体已作推演裁决</small></div><div><strong>${data.provinceCount}</strong><small>逐省连续追溯</small></div><div><strong>${data.checkedYears}</strong><small>年份逐一检查</small></div><div><strong>${data.issues.length}</strong><small>模型一致性错误</small></div>`;
 const corrected=data.endpointInferences.filter(item=>item.reviewType==='boundary-correspondence-correction').length;
 $('audit-policy').textContent=`${publicView.notice(noticeKey('continuity','policy'),data.policy).description} ${data.inferredEndpointProvinceIds.length-corrected}处1820原始空白或冲突采用显式推测${corrected?`，另有${corrected}处已有归属的跨图对应修正`:""}，仍有${data.unresolvedEndpointProvinceIds.length}处未分配。${data.unresolvedSeamProvinceIds?`另按归属、端点和外交关系合并统计，${data.seamExceptions.length}处接缝登记中仍有${data.unresolvedSeamProvinceIds.length}省待补证。`:''}原连续模型核验：${data.status==='passed'?'通过':'存在待修复问题'}；该状态仅对应原报告输入，不表示历史逐年确证或本轮全部验收完成。`;
 $('audit-country').innerHTML+=[...Object.values(assessments.countries)].map(a=>{const c=research.countries.find(c=>c.id===a.countryId);return `<option value="${esc(a.countryId)}">${esc(c?.name_zh||c?.name||a.countryId)} · ${esc(c?.name||'')}</option>`;}).join('');
 const params=new URLSearchParams(location.search);$('audit-country').value=params.get('country')||'';rows=data.provinces;$('audit-province').innerHTML=rows.map(p=>`<option value="${p.id}">${p.id} · ${esc(p.nameZh?p.nameZh+' / '+p.name:p.name)}</option>`).join('');if(rows.some(p=>String(p.id)===params.get('province')))$('audit-province').value=params.get('province');
 $('audit-unresolved').innerHTML=data.endpointInferences.map((item,itemIndex)=>{const p=data.provinces.find(p=>p.id===item.provinceId);return `<p><a href="?province=${p.id}">${p.id} · ${esc(p.name)}</a>：原始${item.reviewType==='boundary-correspondence-correction'?'已有归属的跨图对应待修正':data.sourceConflictProvinceIds.includes(p.id)?'源文件冲突':'底图对应不足'}；推测归属${esc(name(item.historyActor))}。${publicNotice('continuity',['endpointInferences',itemIndex,'reasoning'],item.reasoning)}</p>`;}).join('')+(data.seamExceptions||[]).map((item,itemIndex)=>`<p><a href="?province=${item.provinceId}">${item.provinceId}</a>：${(data.unresolvedSeamProvinceIds||[]).includes(item.provinceId)?'当前仍有未决衔接。':'当前显示已衔接；历史依据仍保留不确定性。原记录：'}${publicNotice('continuity',['seamExceptions',itemIndex,'reason'],item.reason)}</p>`).join('')+(data.unmappedHistoricalChanges||[]).map((item,itemIndex)=>`<p><strong>${esc(publicView.notice(noticeKey('continuity','unmappedHistoricalChanges',itemIndex,'title'),item.title).description)}</strong>（${item.yearStart}—${item.yearEnd}，空间待定位）：${publicNotice('continuity',['unmappedHistoricalChanges',itemIndex,'description'],item.description)}</p>`).join('');
 $('audit-loading').hidden=true;$('audit-view').hidden=false;showCountry();showProvince();
 if(data.regionAuditAvailable){const {loadRegionConsistency}=await import('./region-consistency-ui.js');await loadRegionConsistency(actors);}
 $('audit-country').addEventListener('change',()=>{showCountry();showProvince();});$('audit-province').addEventListener('change',showProvince);$('audit-search').addEventListener('input',filterProvinces);
}catch(e){$('audit-loading').textContent='连续性资料暂未载入，请确认数据已完成构建。';console.error(e);}
